### ISSUE TITLE
Error: Option '--verbose' does not take a value.

### ISSUE THREAD

**Issue by bluppfisk** [econchick/interrogate#142]
### Environment
- `interrogate` version(s) (`interrogate --version`: 1.5.0
- Operating System(s): Debian Bullseye
- Python version(s): 3.9
- Pre-commit version: 3.0.3

### Description of the bug
Having set `--verbose=2` as one of the options in my .pre-commit-config.yaml (full config below), and having run pre-commit during a git commit action, I get the error "

### What you expected to happen
The extra-verbose output from interrogate during pre-commit, as with the `-vv` flag (which does work)

### How to reproduce (as minimally and precisely as possible)
Use the config below in your pre-commit-config.yaml in any repo, run pre-commit install, commit something and behold.

### Anthing else we need to know?
1. `-vv` works!
2. `--verbose` also works, but is not verbose enough
3. **pre-commit-config.yaml:**

```
# Interrogate for docstring coverage
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
    - id: interrogate
      name: check docstring coverage of functions
      args:
        - --ignore-regex=^Base.*$
        - --ignore-regex=^.*Exception$
        - --ignore-regex=^.*Error$
        - --ignore-init-module
        - --ignore-init-method
        - --ignore-module
        - --ignore-magic
        - --ignore-property-decorators
        - --fail-under=90
        - --verbose=2
```
