### ISSUE TITLE
-e/--exclude doesn't work with pre-commit

### ISSUE THREAD

**Issue by ValentinCalomme** [econchick/interrogate#60]
### Environment

- `interrogate` version: 1.3.1
- Operating System(s): Windows
- Python version(s): 3.7.7

### Description of the bug

Using the `-e/--exclude` argument works perfectly fine when using `interrogate` directly on the command line. However, when I pass it in my `.pre-commit-config.yaml` file like so:

```yaml
- repo: https://github.com/econchick/interrogate
      rev: 1.3.1 # or master if you're bold
      hooks:
          - id: interrogate
            args: [--exclude=tests, --fail-under=100]
```
The argument doesn't seem to take effect. So far, I have resulted to using `--ignore-regex` which does work and achieves the same goal. Still, strange that `--exclude` doesn't seem to work. Maybe I am doing something wrong?

### What you expected to happen

I expected `--exclude` to work using pre-commit.

**Comment by econchick** [comment]
Seems like a reasonable expectation :) Thanks for the issue! I'll try to set some time aside over the next week to look deeper into this.

**Comment by ValentinCalomme** [comment]
Thanks a lot!

I am a bit curious about why it doesn't work. One of my guesses is that I am pointed to a directory that doesn't exist given the working directory within pre-commit. But since `interrogate` doesn't throw an error when an exclude pattern isn't found, I can't know for sure.

For my use case, it isn't the most urgent since I can simply ignore test files/functions using a regex.

**Comment by econchick** [comment]
Defining `exclude` in [your project's configuration](https://interrogate.readthedocs.io/en/latest/#configuration) then provide it as an argument to pre-commit could also help if you don't want to get too complicated with regexes ([I do that](https://github.com/econchick/interrogate/blob/master/.pre-commit-config.yaml#L10)). You can also use [pre-commit's exclude](https://pre-commit.com/#top_level-exclude) functionality, too (similarly, [I do that](https://github.com/econchick/interrogate/blob/master/.pre-commit-config.yaml#L9) for sanity, even though it's in my `pyproject.toml`). But yeah I'm definitely curious too, it should work.

**Comment by MarcoGorelli** [comment]
In case it's useful to, as a stopgap solution, you could do
```
- repo: https://github.com/econchick/interrogate
      rev: 1.3.1 # or master if you're bold
      hooks:
          - id: interrogate
            args: [--fail-under=100]
            exclude: ^tests/
```

**Comment by s-weigand** [comment]
My solution is adding [`pass_filenames`](https://pre-commit.com/#hooks-pass_filenames) to the hook
```yaml
        pass_filenames: false
```
That way `interrogate` runs as if you were running it from CLI.

Maybe this should be part of the defaults for the hook?

**Comment by sshishov** [comment]
The same issue as in [isort](https://github.com/PyCQA/isort/issues/938) fixed by [PR 939](https://github.com/PyCQA/isort/pull/939) and [black](https://github.com/psf/black/issues/438) fixed by [PR 1032](https://github.com/psf/black/pull/1032)

Same problem was happening with `flake8` and happening now with [typos](https://github.com/crate-ci/typos/issues/347)

**Comment by joshdunnlime** [comment]
> My solution is adding [`pass_filenames`](https://pre-commit.com/#hooks-pass_filenames) to the hook
> 
> ```yaml
>   - repo: https://github.com/econchick/interrogate
>     rev: 1.3.2
>     hooks:
>       - id: interrogate
>         args: [-vv, --config=pyproject.toml]
>         pass_filenames: false
> ```
> 
> That way `interrogate` runs as if you were running it from CLI.
> 
> Maybe this should be part of the defaults for the hook?

This saved me a LOT of pain. Thank you

**Comment by mathbr10** [comment]
For me this is happening with every argument -i, -I, -m. Any of them work in pre-commit

**Comment by ayushthe1** [comment]
has this issue been fixed yet ?

**Comment by dandluu** [comment]
I also have an issue when I set this in my `propject.toml`. I think it could be exclusive to the `test` folder.

In my `toml` I have for interrogate:

```
# propject.toml
[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
exclude = ["tests", "setup.py", "docs", "build", "cicd_scripts", ".vscode"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
fail-under = 80
verbose = 2
quiet = false
whitelist-regex = []
color = true
generate-badge = "."
badge-format = "svg"
```

Running `pre-commit run --all-files` will fail as it includes the `tests` folder, however if I run `interrogate -c pyproject.toml`
It will show pass and tests will not be included the output.

However, in my `.pre-commit-config.yaml`

If I provide:

```
# .pre-commit-config.yaml
- repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [-c, pyproject.toml]
        exclude: tests
```

`pre-commit run --all-files` will properly exclude tests.
